### ISSUE TITLE
Page Compilation renders HTML to the screen

### ISSUE THREAD

**Issue by davebeesley** [andybelldesign/hylia#34]
I have added a test page via Netlify CMS during my first try out of Hylia.
The result creates a page which is rendered as visible html markup.

Below is the markdown created by Netlify CMS. Not sure if it is related, but it is created in `/page` not `/pages`

```markdown
---
layout: layouts/page.njk
title: Test Page
permalink: test-page
metaTitle: Test Page
metaDesc: Test Page
socialImage: /images/demo-image-1.jpg
---
This is a Test





Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sodales arcu at lacinia sollicitudin. Sed varius laoreet sapien quis vestibulum. Sed pretium hendrerit enim sit amet ultrices. Donec lobortis est ac quam sagittis congue. Vivamus tempus eget erat ut placerat. Morbi consequat quam eu dui euismod feugiat. Praesent vel sapien orci. Suspendisse ante massa, pretium nec leo at, auctor consectetur sem. Nulla nec fermentum diam.



Maecenas rhoncus ultrices viverra. Sed sed tortor convallis, vestibulum metus nec, dapibus est. Fusce venenatis euismod turpis, a venenatis justo euismod vitae. Vivamus ornare eros ac purus elementum, et elementum turpis scelerisque. Vivamus quis purus eros. Vivamus consequat diam ut auctor pulvinar. Pellentesque lorem purus, rutrum vel est ut, convallis aliquam ligula.



Curabitur facilisis non ligula sed maximus. Etiam scelerisque pretium ligula, quis viverra magna gravida et. Nunc vehicula lobortis lectus vel ultrices. Praesent blandit commodo bibendum. Mauris tristique mauris quis ultricies facilisis. Nullam et mauris nec neque euismod gravida id eu enim. Nulla facilisi. Vestibulum facilisis est nec nulla aliquam sagittis. Sed in mi quis metus convallis facilisis. Phasellus molestie tempor dignissim. Aenean faucibus, massa a consectetur commodo, purus enim euismod nibh, vel iaculis dui justo tincidunt est. Morbi non vestibulum odio. Nulla sagittis mauris ac ipsum feugiat pulvinar. Curabitur eu metus quam. Donec suscipit urna ac enim condimentum pretium. Etiam id imperdiet sem, vel semper ligula.



Integer pharetra viverra turpis in tempor. Mauris nec egestas justo. Donec suscipit feugiat tincidunt. Curabitur ac magna quam. Pellentesque molestie, magna ut ultricies posuere, felis tellus condimentum eros, auctor tempor nibh tortor sagittis magna. Etiam pharetra felis turpis, sit amet scelerisque dolor dignissim eu. In et ante rutrum, imperdiet libero vel, interdum libero. Praesent nec felis in massa lobortis tempus eleifend ut purus. Nam vestibulum libero eget quam finibus, quis imperdiet leo efficitur. Sed ornare, turpis sagittis facilisis egestas, sem massa tempus urna, dignissim ultrices neque massa eu erat. Mauris eu tellus eu nibh fermentum interdum.



Suspendisse semper, felis vitae pharetra lacinia, turpis tortor ullamcorper quam, ac malesuada enim neque sed nulla. Aliquam eu gravida libero, eu lacinia dolor. Nulla vel urna lacinia, accumsan erat venenatis, ultricies leo. Vestibulum et nulla vel mi efficitur viverra. Mauris a quam quis magna lobortis venenatis at sed nisi. Praesent et tortor quam. Sed fermentum ipsum ut est suscipit semper. Aliquam ut eleifend risus. Ut tempus velit id mauris rutrum viverra et quis enim. In tristique interdum bibendum. Maecenas sed blandit sem. Duis in metus malesuada, vestibulum nunc vel, cursus felis.
```

**Comment by andybelldesign** [comment]
The `page` directory is a whoopsie, so I'll fix that. 

This is suboptimal (and I'll have to document this well), but if you set the permalink to `/test-page/index.html` [like I do here](https://github.com/andybelldesign/hylia-issue34/commit/09a930604837d4f4fdc530683b487f547c051e7d) it should fix the issue. 

You can see that rendered [page here](https://hylia-issue-34.netlify.com/test-page/).

**Comment by davebeesley** [comment]
Deleted that page and created a new - about page from scratch (after applying your page fix in the attached PR.

Still seeing markup on https://robinstrust.netlify.com/about-the-trust & https://robinstrust.netlify.com/about-the-trust.html
And Page not found on https://robinstrust.netlify.com/about-the-trust/index.html

Pages are populating in the right folder now though

**Comment by davebeesley** [comment]
Just burned everything down, and tried the 1-click deploy. Still an issue

**Comment by davebeesley** [comment]
Assign this to me if you want, I'm determined to fix it :)

**Comment by andybelldesign** [comment]
Awesome, it sounds like your content might be exposing some nasties, so I would really appreciate it if you did look for us!

**Comment by davebeesley** [comment]
I think it is a big chunk of user error, and me assuming 11ty's permalinks work the same way as Jekyll's
When I set the permalink to `about` it follows that literally, and compiles the page to an extentionless file called `about` at the root.
When I set the permalink to `about/index.html` it builds exactly that. Which is exactly what you said in the original fix.

I don't think this is a bug at all, just a nuance of the system.

Close and Won't Fix?

**Comment by andybelldesign** [comment]
Ah no worries. Yeh I can totally sympathise there. Was it that causing the weird markup rendering too?

**Comment by davebeesley** [comment]
I think because the compiled file had no extension, the server was treating it like a text file

**Comment by andybelldesign** [comment]
Fair enough. Well, glad to know there’s no something horrendous going on 🙏
